// change the path of this file to the correct path before using it




// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/models/flutter-logo.glb src/components/HeroModels/FlutterLogo.jsx 
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/flutter-logo.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Node1.geometry} material={materials['#45D1FDFF']} />
//       <mesh geometry={nodes.Node2.geometry} material={materials['#45D1FDFF']} />
//       <mesh geometry={nodes.Node3.geometry} material={materials['#45D1FDFF']} />
//       <mesh geometry={nodes.Node4.geometry} material={materials['#02539AFF']} />
//       <mesh geometry={nodes.Node5.geometry} material={materials['#45D1FDD9']} />
//       <mesh geometry={nodes.Node6.geometry} material={materials['#45D1FDD9']} />
//       <mesh geometry={nodes.Node7.geometry} material={materials['#45D1FD9B']} />
//       <mesh geometry={nodes.Node8.geometry} material={materials['#45D1FD9B']} />
//       <mesh geometry={nodes.Node9.geometry} material={materials['#45D1FB43']} />
//       <mesh geometry={nodes.Node10.geometry} material={materials['#45D2FD76']} />
//     </group>
//   )
// }

// useGLTF.preload('/flutter-logo.glb')
