// change the path of this file to the correct path before using it




// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/models/java-logo.glb src/components/HeroModels/JavaLogo.jsx 
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/java-logo.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Node1.geometry} material={materials['#5382A1FF']} />
//       <mesh geometry={nodes.Node2.geometry} material={materials['#5382A1FF']} />
//       <mesh geometry={nodes.Node3.geometry} material={materials['#5382A1FF']} />
//       <mesh geometry={nodes.Node4.geometry} material={materials['#5382A1FF']} />
//       <mesh geometry={nodes.Node5.geometry} material={materials['#5382A1FF']} />
//       <mesh geometry={nodes.Node6.geometry} material={materials['#5382A1FF']} />
//       <mesh geometry={nodes.Node7.geometry} material={materials['#E76F00FF']} />
//       <mesh geometry={nodes.Node8.geometry} material={materials['#E76F00FF']} />
//       <mesh geometry={nodes.Node9.geometry} material={materials['#55AAAA03']} />
//       <mesh geometry={nodes.Node10.geometry} material={materials['#55AAAA03']} />
//       <mesh geometry={nodes.Node11.geometry} material={materials['#55AAAA03']} />
//       <mesh geometry={nodes.Node12.geometry} material={materials['#55AAAA03']} />
//       <mesh geometry={nodes.Node13.geometry} material={materials['#55AAAA03']} />
//       <mesh geometry={nodes.Node14.geometry} material={materials['#55AAAA03']} />
//     </group>
//   )
// }

// useGLTF.preload('/java-logo.glb')
